### ISSUE TITLE
FPP player and Falcon controllers

### ISSUE THREAD

**Issue by freekeys** [aaknitt/pixel_mapper#2]
Hi, does this work with FPP and Falcon controllers? Or would I have swap out Lumos for something else?

**Comment by aaknitt** [comment]
It works with FPP, you just need to enable E1.31 Inputs and map your FPP channels to E1.31 Universes, keeping in mind that the max number of channels per Universe is 512.  3 channels per pixel => 510 usable channels per Universe.  Make sure FPP isn't trying to play anything when you're sending commands via E1.31/Lumos.  

![image](https://github.com/aaknitt/pixel_mapper/assets/13441553/b44ceb2c-6aa5-4e65-acea-d37d3cce1fec)

**Comment by freekeys** [comment]
Thanks so much, really helpful!
